version : '3'

services: 

  ts_express:
    build: api
    container_name: ts_express_docker_templete
    restart: always
    volumes:
      - ./api/src:/app/src
    ports: 
      - 3000:3000
    user:
      node:node
    stdin_open: true
    environment: 
      - ENV=DEV